# Generated by Django 5.0.4 on 2024-04-22 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodeDetails',
            fields=[
                ('countryname', models.CharField(max_length=25, verbose_name='Vendor Country Name')),
                ('countrycode', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Country Code')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclename', models.CharField(max_length=50, verbose_name='Vehicle Name')),
                ('vehicleregno', models.CharField(max_length=50, unique=True, verbose_name='Vehicle Reg No')),
                ('vehicletype', models.CharField(max_length=50, verbose_name='Vehicle Type')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPSDeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceserialno', models.CharField(max_length=50, unique=True, verbose_name='GPSDevice Serial No')),
                ('installedat', models.DateTimeField(auto_now=True, verbose_name='GPSDevice Installed Date')),
                ('expiredat', models.DateTimeField(verbose_name='GPSDevice Expirty Date')),
                ('veciclename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vehicledetails')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('vendorname', models.CharField(max_length=50, verbose_name='Vendor name')),
                ('vendorid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Vendor ID')),
                ('vendoraddress', models.TextField(verbose_name='Vendor Address')),
                ('vendormob1', models.IntegerField(unique=True, verbose_name='Vendor Mobile no_1')),
                ('vendormob2', models.IntegerField(verbose_name='Vendor Mobile no_2')),
                ('vendordistrict', models.CharField(max_length=50, verbose_name='Vendor District')),
                ('isactive', models.BooleanField(verbose_name=' Active or Not')),
                ('vendorcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.countrycodedetails')),
            ],
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vendorid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vendorprofile'),
        ),
    ]
