# Generated by Django 5.0.4 on 2024-04-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclename', models.CharField(max_length=50, verbose_name='Vehicle Name')),
                ('vehicleregno', models.CharField(max_length=50, verbose_name='Vehicle Reg No')),
                ('vehicletype', models.CharField(max_length=50, verbose_name='Vehicle Type')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPSDeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceserialno', models.CharField(max_length=50, verbose_name='GPSDevice Serial No')),
                ('installedat', models.DateTimeField(auto_now=True, verbose_name='GPSDevice Installed Date')),
                ('expiredat', models.DateTimeField(verbose_name='GPSDevice Expirty Date')),
                ('veciclename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vehicledetails')),
            ],
        ),
    ]
