# Generated by Django 5.0.4 on 2024-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdevicedetails',
            name='deviceserialno',
            field=models.CharField(max_length=50, unique=True, verbose_name='GPSDevice Serial No'),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicleregno',
            field=models.CharField(max_length=50, unique=True, verbose_name='Vehicle Reg No'),
        ),
    ]
