# Generated by Django 5.0.4 on 2024-04-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='vendorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vendorprofile'),
        ),
    ]
