# Generated by Django 5.0.2 on 2024-04-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_vehiclegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehiclemake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vehiclemake'),
        ),
    ]
