# Generated by Django 5.0.4 on 2024-04-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_alter_vehicledetails_vendorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsdevicedetails',
            old_name='veciclename',
            new_name='vehiclename',
        ),
        migrations.CreateModel(
            name='GPSDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving', models.BooleanField(verbose_name='GPS Device Move Status')),
                ('stopped', models.BooleanField(verbose_name='GPS Device Stopped Status')),
                ('idlling', models.BooleanField(verbose_name='GPS Device Idlling Status')),
                ('offline', models.BooleanField(verbose_name='GPS Device Offline Status')),
                ('subsexpired', models.BooleanField(verbose_name='GPS Device Subscription Expiry Status')),
                ('ignition', models.BooleanField(verbose_name='GPS Device Ignition Status')),
                ('gpssignal', models.CharField(max_length=50, verbose_name='GPS Signal Status')),
                ('speed', models.IntegerField(verbose_name='GPS Device Speed')),
                ('orientationvalue', models.IntegerField(verbose_name='GPS Device Orientation value')),
                ('deviceexternalpower', models.BooleanField(verbose_name='GPS Device External Power Status')),
                ('location', models.TextField(verbose_name='GPS Device Location')),
                ('temperature', models.IntegerField(verbose_name='GPS Device temperature')),
                ('internalbatterypower', models.IntegerField(verbose_name='GPS Device Internal Battery Power')),
                ('movmentvalue', models.IntegerField(verbose_name='GPS Device Movement Value')),
                ('gsmstrength', models.FloatField(verbose_name='GPS Device GSM Strength')),
                ('lat', models.FloatField(verbose_name='GPS Device Latitude')),
                ('long', models.FloatField(verbose_name='GPS Device Longitude')),
                ('deviceserialno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.gpsdevicedetails')),
            ],
        ),
    ]
