# Generated by Django 5.0.4 on 2024-04-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_rename_veciclename_gpsdevicedetails_vehiclename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='HomeApp.userprofile'),
            preserve_default=False,
        ),
    ]
