# Generated by Django 5.0.4 on 2024-04-22 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_countrycodedetails_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycodedetails',
            name='countrycode',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Country Code'),
        ),
    ]
