# Generated by Django 5.0.2 on 2024-04-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_alter_vehiclefueltype_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('phoneno1', models.CharField(max_length=50, verbose_name='Driver Mob No1')),
                ('phoneno2', models.CharField(max_length=50, null=True, verbose_name='Driver Mob No2')),
                ('vehiclename', models.CharField(max_length=50, null=True, verbose_name='Vehicle Name')),
                ('licenseno', models.CharField(max_length=50, verbose_name='License No')),
                ('guarantorname', models.CharField(max_length=50, null=True, verbose_name='Guarantor Name')),
                ('guarandorphoneno', models.CharField(max_length=50, null=True, verbose_name='Guarantor Mob No')),
                ('aadharno', models.CharField(max_length=50, verbose_name='Aadhar Number')),
                ('licenseissuedate', models.DateField()),
                ('licenseexpirtydate', models.DateField()),
                ('driverid', models.CharField(max_length=50, verbose_name='Driver ID')),
                ('driverimage', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Driver Image')),
                ('pancardimage', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='pancard Image')),
                ('driverlicense', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Driver license')),
                ('drivermisc', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Driver Miscellaneous')),
                ('countrycode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.countrycodedetails')),
                ('vehicleregno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vehicledetails')),
            ],
        ),
    ]
