# Generated by Django 5.0.2 on 2024-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_driverdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetails',
            name='vehiclename',
        ),
    ]
