# Generated by Django 5.0.2 on 2024-04-27 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0006_remove_driverdetails_vehiclename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='countrycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.countrycodedetails'),
        ),
    ]
