# Generated by Django 5.0.2 on 2024-04-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_alter_driverdetails_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='driverid',
            field=models.CharField(max_length=50, unique=True, verbose_name='Driver ID'),
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.CharField(unique=True, verbose_name='Trip ID')),
                ('tripsourceplace', models.CharField(max_length=50, verbose_name='Trip Source Place')),
                ('tripstarttime', models.TimeField(verbose_name='Trip Start Time')),
                ('tripdestinationplace', models.CharField(max_length=50, verbose_name='Trip Destination Place')),
                ('tripendtime', models.TimeField(verbose_name='Trip End Time')),
                ('tripstate', models.CharField(max_length=50, verbose_name='Trip State')),
                ('driverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.driverdetails')),
                ('gpsdeviceserialno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.gpsdevicedetails')),
                ('vehicleregno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.vehicledetails')),
            ],
        ),
    ]
