# Generated by Django 5.0.2 on 2024-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0008_alter_driverdetails_driverid_tripdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='tripname',
            field=models.CharField(default=1, max_length=50, verbose_name='Trip Name'),
            preserve_default=False,
        ),
    ]
