# Generated by Django 5.0.2 on 2024-04-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0009_tripdetails_tripname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Routeid', models.CharField(max_length=50, unique=True, verbose_name='Route ID')),
                ('routename', models.CharField(max_length=50, verbose_name='Route Name')),
                ('stop1', models.CharField(max_length=50, verbose_name='Stop 1')),
                ('stop2', models.CharField(max_length=50, verbose_name='Stop 2')),
                ('stop3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 3')),
                ('stop4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 4')),
                ('stop5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 5')),
                ('stop6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 6')),
                ('stop7', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 7')),
                ('stop8', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 8')),
                ('stop9', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 9')),
                ('stop10', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 10')),
                ('stop11', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 11')),
                ('stop12', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 12')),
                ('stop13', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 13')),
                ('stop14', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 14')),
                ('stop15', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stop 15')),
            ],
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='tripname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.routedetails'),
        ),
    ]
