# Generated by Django 5.0.2 on 2024-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0010_routedetails_alter_tripdetails_tripname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routedetails',
            old_name='Routeid',
            new_name='routeid',
        ),
    ]
