# Generated by Django 5.0.2 on 2024-04-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0011_rename_routeid_routedetails_routeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscripmode', models.CharField(max_length=50, unique=True, verbose_name='Subscription Status Mode')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptioncode', models.CharField(max_length=50, unique=True, verbose_name='Subscription Code')),
                ('expireson', models.DateTimeField(verbose_name='Expires On')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('devicesrno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.gpsdevicedetails')),
                ('subscriptionstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.subscriptionmode')),
            ],
        ),
    ]
