# Generated by Django 5.0.4 on 2024-04-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0012_subscriptionmode_subscriptiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='durationno',
            field=models.IntegerField(default=0, verbose_name='Duration in Numbers'),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='durationperiod',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default=0, max_length=50, verbose_name='Duration Period'),
            preserve_default=False,
        ),
    ]
