# Generated by Django 5.0.2 on 2024-04-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0013_subscriptiondetails_durationno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='indays',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duration in Days'),
        ),
    ]
