# Generated by Django 5.0.2 on 2024-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0014_subscriptiondetails_indays'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='startson',
            field=models.DateTimeField(default='2024-4-30 00:00:00', verbose_name='Subscription Starts On'),
            preserve_default=False,
        ),
    ]
