# Generated by Django 5.0.2 on 2024-04-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0015_subscriptiondetails_startson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='indays',
            new_name='remaindays',
        ),
    ]
