# Generated by Django 5.0.2 on 2024-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0016_rename_indays_subscriptiondetails_remaindays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='remaindays',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Expiry Remaining Days'),
        ),
    ]
